<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <RootNamespace>Shiny.SmartBle.Tests</RootNamespace>
        <NoWarn>$(NoWarn);xUnit1051</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="xunit.runner.visualstudio" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\Shiny.SmartBle\Shiny.SmartBle.csproj" />
        <ProjectReference Include="..\..\src\Shiny.SmartBle.Client\Shiny.SmartBle.Client.csproj" />
        <ProjectReference Include="..\..\src\Shiny.SmartBle.Host\Shiny.SmartBle.Host.csproj" />
        <ProjectReference Include="..\..\src\Shiny.SmartBle.SourceGenerators\Shiny.SmartBle.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>
</Project>
