<Project>
    <ItemGroup>
        <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup Condition="'$(IsPackable)' != 'false'">
        <None Include="$(MSBuildThisFileDirectory)nuget.png" Pack="true" PackagePath="icon.png" Visible="false" />
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\" Visible="false" />
    </ItemGroup>
</Project>
