<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Nerdbank.GitVersioning" Version="3.10.94" />
        <PackageVersion Include="Shiny.Extensions.Serialization" Version="5.3.1" />
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
        <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
        <PackageVersion Include="Shiny.BluetoothLE" Version="5.8.1" />
        <PackageVersion Include="Shiny.BluetoothLE.Hosting" Version="5.8.1" />
        <PackageVersion Include="Shiny.Hosting.Maui" Version="5.8.1" />
        <PackageVersion Include="Shiny.Maui.Shell" Version="7.0.1" />
        <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.7" />
        <PackageVersion Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
        <PackageVersion Include="xunit.v3" Version="3.2.2" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    </ItemGroup>
</Project>
