blank_issues_enabled: false
contact_links:
  - name: Shiny.BluetoothLE.Hubs Discussions
    url: https://github.com/shinyorg/bluetoothle-hubs/discussions
    about: Please ask and answer questions here.
