using System.Linq;
using System.Text;

namespace Shiny.BluetoothLE.Hubs.SourceGenerators;

static class Emitter
{
    const string Header = "// <auto-generated by Shiny.BluetoothLE.Hubs.SourceGenerators />\n#nullable enable\n#pragma warning disable CS1591, CA2255\n";
    const string GeneratedCode = "[global::System.CodeDom.Compiler.GeneratedCode(\"Shiny.BluetoothLE.Hubs\", \"1.0\")]";


    public static string ClientProxy(ContractModel c)
    {
        var access = c.IsPublic && c.IsLocal ? "public" : "internal";
        var sb = new StringBuilder(Header);
        OpenNamespace(sb, c.Namespace);

        sb.AppendLine($"/// <summary>Generated client proxy for <see cref=\"{c.FullName.Replace("global::", "")}\"/></summary>");
        sb.AppendLine(GeneratedCode);
        sb.AppendLine($"{access} sealed partial class {c.ProxyName} : global::Shiny.BluetoothLE.Hubs.BleHubClient, {c.FullName}, global::Shiny.BluetoothLE.Hubs.IBleHubClient<{c.FullName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public {c.ProxyName}(global::Shiny.BluetoothLE.Hubs.BleHubClientServices services, string serviceUuid, string characteristicUuid)");
        sb.AppendLine("        : base(services, serviceUuid, characteristicUuid) { }");
        sb.AppendLine();
        sb.AppendLine($"    public {c.FullName} Hub => this;");
        sb.AppendLine();

        foreach (var m in c.Methods)
        {
            var parameters = string.Join(", ", m.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var token = m.Parameters.FirstOrDefault(p => p.IsCancellationToken)?.Name ?? "default";
            var args = "this.CreateArguments()" + string.Concat(m.Parameters.Where(p => !p.IsCancellationToken).Select(p => $".Write<{p.Type}>({p.Name})"));

            var body = m.ReturnKind switch
            {
                ReturnKind.Task => $"this.InvokeVoidCore(\"{m.Name}\", {args}, {token})",
                ReturnKind.TaskOfT => $"this.InvokeCore<{m.ResultType}>(\"{m.Name}\", {args}, {token})",
                _ => $"this.StreamCore<{m.ResultType}>(\"{m.Name}\", {args}, {token})"
            };
            sb.AppendLine($"    public {m.ReturnType} {Escape(m.Name)}({parameters})");
            sb.AppendLine($"        => {body};");
            sb.AppendLine();
        }

        foreach (var e in c.Events)
            sb.AppendLine($"    public event {e.DelegateType} {Escape(e.Name)} = null!;");

        sb.AppendLine();
        sb.AppendLine("    protected override void OnPush(string name, global::Shiny.BluetoothLE.Hubs.BleHubArgumentReader args)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (name)");
        sb.AppendLine("        {");
        foreach (var e in c.Events)
        {
            sb.AppendLine($"            case \"{e.Name}\":");
            sb.AppendLine("            {");
            sb.AppendLine($"                args.Expect({e.ArgumentTypes.Count}, \"{e.Name}\");");
            for (var i = 0; i < e.ArgumentTypes.Count; i++)
                sb.AppendLine($"                var a{i} = args.Read<{e.ArgumentTypes.Items[i]}>();");
            var callArgs = string.Join(", ", Enumerable.Range(0, e.ArgumentTypes.Count).Select(i => "a" + i));
            sb.AppendLine($"                this.{Escape(e.Name)}?.Invoke({callArgs});");
            sb.AppendLine("                break;");
            sb.AppendLine("            }");
        }
        sb.AppendLine("            default:");
        sb.AppendLine("                this.OnUnknownPush(name);");
        sb.AppendLine("                break;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine($"    internal static void RegisterBleHubClient() => global::Shiny.BluetoothLE.Hubs.BleHubClientFactories.Register<{c.FullName}, {c.ProxyName}>(");
        sb.AppendLine($"        static (services, serviceUuid, characteristicUuid) => new {c.ProxyName}(services, serviceUuid, characteristicUuid)");
        sb.AppendLine("    );");
        sb.AppendLine("}");
        CloseNamespace(sb, c.Namespace);
        return sb.ToString();
    }


    public static string PushExtensions(ContractModel c)
    {
        var access = c.IsPublic && c.IsLocal ? "public" : "internal";
        var sb = new StringBuilder(Header);
        OpenNamespace(sb, c.Namespace);

        sb.AppendLine($"/// <summary>Typed host to client pushes for <see cref=\"{c.FullName.Replace("global::", "")}\"/> - use from a hub (Clients.All...) or IHubContext</summary>");
        sb.AppendLine(GeneratedCode);
        sb.AppendLine($"{access} static class {c.PushExtensionsName}");
        sb.AppendLine("{");
        foreach (var e in c.Events)
        {
            var parameters = string.Concat(e.ArgumentTypes.Items.Select((t, i) => $", {t} {e.ArgumentNames.Items[i]}"));
            var args = "push.CreateArguments()" + string.Concat(e.ArgumentTypes.Items.Select((t, i) => $".Write<{t}>({e.ArgumentNames.Items[i]})"));
            sb.AppendLine($"    public static global::System.Threading.Tasks.Task {Escape(e.Name)}(this global::Shiny.BluetoothLE.Hubs.BleHubPush<{c.FullName}> push{parameters}, global::System.Threading.CancellationToken cancellationToken = default)");
            sb.AppendLine($"        => push.Send(\"{e.Name}\", {args}, cancellationToken);");
            sb.AppendLine();
        }
        sb.AppendLine("}");
        CloseNamespace(sb, c.Namespace);
        return sb.ToString();
    }


    public static string HubDispatcher(HubModel h)
    {
        var c = h.Contract;
        var className = h.MetadataSafeName + "_BleHubDispatcher";
        var sb = new StringBuilder(Header);
        sb.AppendLine("namespace Shiny.BluetoothLE.Hubs.Generated");
        sb.AppendLine("{");
        sb.AppendLine(GeneratedCode);
        sb.AppendLine($"internal sealed class {className} : global::Shiny.BluetoothLE.Hubs.BleHubDispatcher<{h.FullName}, {c.FullName}>");
        sb.AppendLine("{");

        // method kinds
        sb.AppendLine("    public override global::Shiny.BluetoothLE.Hubs.BleHubMethodKind GetMethodKind(string method) => method switch");
        sb.AppendLine("    {");
        foreach (var m in c.Methods)
        {
            var kind = m.ReturnKind == ReturnKind.AsyncEnumerable ? "Stream" : "Invoke";
            sb.AppendLine($"        \"{m.Name}\" => global::Shiny.BluetoothLE.Hubs.BleHubMethodKind.{kind},");
        }
        sb.AppendLine("        _ => global::Shiny.BluetoothLE.Hubs.BleHubMethodKind.NotFound");
        sb.AppendLine("    };");
        sb.AppendLine();

        // invoke
        sb.AppendLine($"    public override async global::System.Threading.Tasks.Task<byte[]?> Invoke({h.FullName} hub, string method, global::Shiny.BluetoothLE.Hubs.BleHubArgumentReader args, global::Shiny.BluetoothLE.Hubs.IBleHubSerializer serializer, global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        var invokes = c.Methods.Where(x => x.ReturnKind != ReturnKind.AsyncEnumerable).ToList();
        if (invokes.Count > 0)
        {
            sb.AppendLine("        switch (method)");
            sb.AppendLine("        {");
        }
        foreach (var m in invokes)
        {
            sb.AppendLine($"            case \"{m.Name}\":");
            sb.AppendLine("            {");
            var call = ReadArgsAndCall(sb, m, h);
            if (m.ReturnKind == ReturnKind.Task)
            {
                sb.AppendLine($"                await {call}.ConfigureAwait(false);");
                sb.AppendLine("                return null;");
            }
            else
            {
                sb.AppendLine($"                var result = await {call}.ConfigureAwait(false);");
                sb.AppendLine($"                return serializer.Serialize<{m.ResultType}>(result);");
            }
            sb.AppendLine("            }");
        }
        if (invokes.Count > 0)
            sb.AppendLine("        }");
        sb.AppendLine("        await global::System.Threading.Tasks.Task.CompletedTask.ConfigureAwait(false);");
        sb.AppendLine("        throw this.MethodNotFound(method);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // stream
        sb.AppendLine($"    public override global::System.Collections.Generic.IAsyncEnumerable<byte[]> Stream({h.FullName} hub, string method, global::Shiny.BluetoothLE.Hubs.BleHubArgumentReader args, global::Shiny.BluetoothLE.Hubs.IBleHubSerializer serializer, global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        var streams = c.Methods.Where(x => x.ReturnKind == ReturnKind.AsyncEnumerable).ToList();
        if (streams.Count > 0)
        {
            sb.AppendLine("        switch (method)");
            sb.AppendLine("        {");
        }
        foreach (var m in streams)
        {
            sb.AppendLine($"            case \"{m.Name}\":");
            sb.AppendLine("            {");
            var call = ReadArgsAndCall(sb, m, h);
            sb.AppendLine($"                return SerializeStream<{m.ResultType}>({call}, serializer, cancellationToken);");
            sb.AppendLine("            }");
        }
        if (streams.Count > 0)
            sb.AppendLine("        }");
        sb.AppendLine("        throw this.MethodNotFound(method);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine($"    internal static void RegisterBleHub() => global::Shiny.BluetoothLE.Hubs.BleHubDispatchers.Register(new {className}());");
        sb.AppendLine("}");
        sb.AppendLine("}");
        sb.AppendLine();

        // IHubContext<THub>.Clients - a C# 14 extension property, typed to the hub's contract
        var access = h.IsPublic && c.IsPublic ? "public" : "internal";
        OpenNamespace(sb, h.Namespace);
        sb.AppendLine(GeneratedCode);
        sb.AppendLine($"{access} static class {h.Name}ContextExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    extension(global::Shiny.BluetoothLE.Hubs.IHubContext<{h.FullName}> context)");
        sb.AppendLine("    {");
        sb.AppendLine($"        /// <summary>Typed push targets for {h.Name} - eg. Clients.All.SomeEvent(...)</summary>");
        sb.AppendLine($"        public global::Shiny.BluetoothLE.Hubs.IHubClients<global::Shiny.BluetoothLE.Hubs.BleHubPush<{c.FullName}>> Clients => context.GetClients<{c.FullName}>();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        CloseNamespace(sb, h.Namespace);
        return sb.ToString();
    }


    static string ReadArgsAndCall(StringBuilder sb, MethodModel m, HubModel h)
    {
        var wire = m.Parameters.Where(x => !x.IsCancellationToken).ToList();
        sb.AppendLine($"                args.Expect({wire.Count}, \"{m.Name}\");");
        for (var i = 0; i < wire.Count; i++)
            sb.AppendLine($"                var a{i} = args.Read<{wire[i].Type}>();");

        var callArgs = Enumerable.Range(0, wire.Count).Select(i => "a" + i).ToList();
        var binding = h.Bindings.FirstOrDefault(x => x.Name == m.Name);
        if (binding?.PassCancellationToken == true)
            callArgs.Add("cancellationToken");

        return $"hub.{Escape(m.Name)}({string.Join(", ", callArgs)})";
    }


    static void OpenNamespace(StringBuilder sb, string? ns)
    {
        if (ns != null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }
    }


    static void CloseNamespace(StringBuilder sb, string? ns)
    {
        if (ns != null)
            sb.AppendLine("}");
    }


    static string Escape(string name) => Microsoft.CodeAnalysis.CSharp.SyntaxFacts.GetKeywordKind(name) != Microsoft.CodeAnalysis.CSharp.SyntaxKind.None ? "@" + name : name;
}
